INSERT INTO "CUSTOMER" (ID, NAME, REGDTTM) VALUES(1, 'keira', TO_DATE('2018-04-17', 'yyyy-mm-dd'));
INSERT INTO "CUSTOMER" (ID, NAME, REGDTTM) VALUES(2, 'frank', TO_DATE('2018-04-17', 'yyyy-mm-dd'));
INSERT INTO "CUSTOMER" (ID, NAME, REGDTTM) VALUES(3, 'kai', TO_DATE('2018-04-17', 'yyyy-mm-dd'));