spring:
  profiles:
    active: local

my:
  profile: ${spring.profiles.active}
  secret : ${random.value}
  number : ${random.int}
  bignumber : ${random.long}
  uuid : ${random.uuid}
  number.less.than.ten : ${random.int(10)}
  number.in.range : ${random.int[1024,65536]}
  members :
    - genos
    - frank

---

spring:
  profiles: local

server:
  port: 8080

my:
  members : #this will not be merged but replaced.
    - keira
    - kai

---

spring:
  profiles: real

server:
  port: 80

my:
  members : #this will not be merged but replaced.
    - chris
    - daniel